### ISSUE TITLE
Coub unavailable

### ISSUE THREAD

**Issue by wankio** [HelpSeeker/CoubDownloader#1]
every links always have same problem : Error: Coub unavailable

**Comment by HelpSeeker** [comment]
Could you please post a link that doesn't work for you and the output of `youtube-dl -v <link>`?

**Comment by HelpSeeker** [comment]
I'm closing this issue for now.

If the problem still persists, then please post additional information as mentioned in my previous comment. Without it I can only guess that youtube-dl is either missing (not installed or not part of your PATH) or outdated.

**Comment by wankio** [comment]
oh nvm, it still downloaded non-playable file :)
