### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Andrut184** [HelpSeeker/CoubDownloader#10]
I've done everything as you wrote in README in confiogration. Then i opened coub.py in cmd and i got SyntaxError(attached screenshot). I'm not advanced in python and english, so sorry if i made language mistakes. 
![error](https://user-images.githubusercontent.com/69591250/90128492-3f348d00-dd67-11ea-8879-47c55c1df85b.png)

**Comment by HelpSeeker** [comment]
What Python version are you using (`python --version`)? It seems like the interpreter doesn't recognize f-strings, which were introduced with Python 3.6.

The script needs at least Python 3.7 to work.

**Comment by Andrut184** [comment]
> What Python version are you using (`python --version`)? It seems like the interpreter doesn't recognize f-strings, which were introduced with Python 3.6.
> 
> The script needs at least Python 3.7 to work.

**Comment by Andrut184** [comment]
Old version of python was reason of my issue. Thanks for quick help.
