### ISSUE TITLE
Certificate verification failed! Please update your CA certificates

### ISSUE THREAD

**Issue by XimikRU** [HelpSeeker/CoubDownloader#12]
Hi. I was using coub.py script for backuping my channel, but today it showed this error message:

```
Certificate verification failed! Please update your CA certificates
```

I tried both on macOS 10.15.6 and Win 8.1 machine - same. I am concerned that this problem is shared between 2 independent OS... Can you point me the way of solving the problem (I don't know much about certificates)? Is the problem on my side or on the package side. I tried to google, but it seems that many things can cause this problem. Can u have a quick look on this, please? Thanks!

Great tool, btw. I am using this script as embed module in my multi-tool, that's why I was very sad seeing its not working anymore :(

**Comment by HelpSeeker** [comment]
Could you please run
```
python -c "import ssl; print(ssl.get_default_verify_paths())"
```
and post the output?

I assume the problem lies with your installation. Specifically for MacOS I remember reading how they ship Python with its own OpenSSL version since Python 3.6, which meant not having access to the OS certificates anymore and could be resolved by either running a post-installation script or installing certifi.

**Comment by XimikRU** [comment]
Python 2.7.16
python -c "import ssl; print(ssl.get_default_verify_paths())"
```
DefaultVerifyPaths(cafile='/private/etc/ssl/cert.pem', capath='/private/etc/ssl/certs', openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/private/etc/ssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/private/etc/ssl/certs')
```

Python 3.9.7
python3 -c "import ssl; print(ssl.get_default_verify_paths())"
```
DefaultVerifyPaths(cafile=None, capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/Library/Frameworks/Python.framework/Versions/3.9/etc/openssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/Library/Frameworks/Python.framework/Versions/3.9/etc/openssl/certs')
```

**Comment by HelpSeeker** [comment]
Could you try running `Install Certificates.command` located in `Applications/Python 3.9` and see if that solves the issue?

**Comment by XimikRU** [comment]
Yes, it worked! Thank you for help and for the tool! Cant imagine backing up all my channels without it!
