### ISSUE TITLE
 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by dmrost** [HelpSeeker/CoubDownloader#13]
I chose Output: %title% and i get error:
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f60c' in position 43: character maps to <undefined>

Perhaps is similar: https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters

**Comment by HelpSeeker** [comment]
Could you also please post the link of the coub or its id?

**Comment by OmlineEditor** [comment]
I have a similar problem
when the program starts, an error message is displayed

![изображение_2022-03-18_005048](https://user-images.githubusercontent.com/13348933/158900561-6adbdbb7-da2e-4767-8a65-fa9b625f5cdf.png)


Traceback (most recent call last):
  File "coub-gui.py", line 303, in <module>
  File "coub.py", line 1995, in main
  File "coub.py", line 1960, in attempt_process
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "coub.py", line 1929, in process
  File "coub.py", line 1109, in process
  File "coub.py", line 1031, in merge
  File "C:\Users\MET\Desktop\CoubDownloader\python-3.7.7-x86_64\lib\encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 20-22: character maps to <undefined>

My system: Windows 7 x64

https://coub.com/view/30to4e


how to solve the problem?

**Comment by HelpSeeker** [comment]
The issue should be fixed now. Please download and run the files from master until I get around creating new EXE files.

If you have further problems with filenames, also check out the dev branch. Its special character handling is a lot more strict (only available as CLI though).

**Comment by OmlineEditor** [comment]
can you add an option so that all characters except the selected ones are deleted?
only these selected ones are allowed: [a-z] [A-Z] [0-9] [ _ - ) ( = + # $ ! % &]
and if possible, the selected letters of the national alphabet (Russian for example): [а-я] [А-Я]
this will help solve the problem if there are problematic characters in the future.

PS  when will there be a new GUI exe file?

**Comment by HelpSeeker** [comment]
The dev version is more strict in that regard, so if you want to be safe (and don't mind using CLI), you can switch to it instead. Given how soon Coub will shut down, I don't plan on merging the dev changes into the master branch anymore.

As for the EXE files, I haven't used the master version of CoubDownloader in years. I gotta set up my environment again first. I plan on doing it this evening though.

**Comment by OmlineEditor** [comment]
Well, thank you for the program. she helped me a lot.
