### ISSUE TITLE
the parameter "--connections N" does not work

### ISSUE THREAD

**Issue by OmlineEditor** [HelpSeeker/CoubDownloader#15]
if you run a script from the console to download from the channel, then the download takes place in 1 then always. if you use a graphical environment, then downloads can take place in several streams at the same time.

the problem can be identified by the download speed and the number of mp3 files in the download folder. from the console there is always no more than 1 mp3 file.

**Comment by HelpSeeker** [comment]
I'm currently not able to reproduce this error. Be it with the pre-packaged version or from master (with updated dependencies).

In any case, CoubDownloader only takes the value from --connections and passes it directly to aiohttp, which then does its own thing. If aiohttp doesn't honor the given limit, then it's most likely a bug on their end. Although - again - I haven't been able to reproduce it on my machine.

**Comment by HelpSeeker** [comment]
Did you set the number of connections via configuration file or with the CLI/GUI?

**Comment by OmlineEditor** [comment]
in the command line, I specified the parameter:
`python.exe coub.py -c chanel.example --connections 10 -p .\coub -o "%title%  %id%"`

**Comment by HelpSeeker** [comment]
I see. So it's about not using enough connections. Do you have aiohttp installed?

**Comment by OmlineEditor** [comment]
aiohttp - I didn't install any extras.
it looks like it's not a bug, but my fault. I haven't installed any additional software.
I didn't read the instructions carefully, sorry.
