### ISSUE TITLE
[WinError 123] The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by iG8R** [HelpSeeker/CoubDownloader#16]
Hi.
I face an error mentioned in the title while trying to change Output directory to anything else but default.
With the default Output directory coub-gui.exe works OK.
Thanks in advance.

```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002415889F790>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Traceback (most recent call last):
  File "coub-gui.py", line 303, in <module>
  File "coub.py", line 1981, in main
  File "coub.py", line 1558, in resolve_paths
  File "os.py", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\" --merge-ext mkv --name-template %title%-%id%'
```

**Comment by Magellano** [comment]
> Hi. I face an error mentioned in the title while trying to change Output directory to anything else but default. With the default Output directory coub-gui.exe works OK. Thanks in advance.
> 
> ```
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002415889F790>
> Traceback (most recent call last):
>   File "asyncio\proactor_events.py", line 116, in __del__
>   File "asyncio\proactor_events.py", line 108, in close
>   File "asyncio\base_events.py", line 751, in call_soon
>   File "asyncio\base_events.py", line 515, in _check_closed
> RuntimeError: Event loop is closed
> Traceback (most recent call last):
>   File "coub-gui.py", line 303, in <module>
>   File "coub.py", line 1981, in main
>   File "coub.py", line 1558, in resolve_paths
>   File "os.py", line 225, in makedirs
> OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\" --merge-ext mkv --name-template %title%-%id%'
> ```

This script has problems with symbols (emojis, special characters, etc.). If the name COUB contains such symbols, the script will give an error. You can try using other scripts to save videos from COUB. For example, this https://github.com/Bukk94/CoubDownloader or https://github.com/DrNoLife/coub_downloader

**Comment by iG8R** [comment]
@Magellano 
Thanks for the links, but, "**With the default Output directory coub-gui.exe works OK.**" I.e. with the default Output directory all coubs are downloaded just fine. The error occurs only with custom Output directory, in my case it's "D:\". And what is a weird quotation mark after D:\\ here 'D:\\" --merge-ext mkv --name-template %title%-%id%'?

**Comment by HelpSeeker** [comment]
This appears to be a problem with Gooey.
https://github.com/chriskiehl/Gooey/issues/336
Selecting only the drive doesn't strip the trailing backslash from the selected path, which makes the option parsing of the tab fail.

Try removing the backslash manually, then it should work.
![Screenshot (40)](https://user-images.githubusercontent.com/36918959/159168524-ebae8fbc-54d4-4cf8-aa14-935d2f8b4cc9.png)

**Comment by iG8R** [comment]
@HelpSeeker 
Thank you very much:) It works.

**Comment by Magellano** [comment]
@iG8R are you sure that everything loads perfectly in the gui? If there are characters in the name of the video, as I wrote above, it gives an error
For example, this Coub - https://coub.com/view/19452g
Here is the error
```### Parse Input ###

Reading command line:
  1 link found

Results:
  1 link

### Download Coubs ###

Traceback (most recent call last):
  File "coub-gui.py", line 303, in <module>
  File "coub.py", line 1995, in main
  File "coub.py", line 1960, in attempt_process
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "coub.py", line 1929, in process
  File "coub.py", line 1109, in process
  File "coub.py", line 1031, in merge
  File "C:\Users\MET\Desktop\CoubDownloader\python-3.7.7-x86_64\lib\encodings\cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f408' in position 34: character maps to <undefined>
```

@HelpSeeker Can you tell me what the reason is?)

Since there is an emoji in the name (this also applies to other characters - **_? : |_** etc.) Yes, in Windows they cannot be used in the name of files, but perhaps there is some way to make an automatic replacement?

**Comment by HelpSeeker** [comment]
Works with the new hotfix release on my Win10 machine.
![Screenshot (42)](https://user-images.githubusercontent.com/36918959/159169948-949bdbcc-eb7d-4a4a-8b06-a02aa9823329.png)

The problem wasn't creating a file with an emoji character in the name, but rather writing the name into a text file, which is used by FFmpeg to loop the video. The standard character encoding was the issue.

You are right though, that the master branch isn't very sophisticated, when it comes to exotic symbols. It only removes the following list of characters for all OSes:
- \n
- \t
- '
- /

As well as these characters on Windows:
- <
- \>
- :
- "
- \
- |
- ?
- \*

However, if a file cannot be created because of filename issues, CoubDownloader will automatically fall back to %id% as the filename. That means funny characters will often lead to basic ID filenames, not download failure. The dev branch handles this better by trying to remove/replace problematic characters on a much wider scope.

**Comment by iG8R** [comment]
@Magellano 
Your coub did have no problem with downloading process despite errors in the logs.
```
### Parse Input ###

Reading command line:
  1 link found

Results:
  1 link

### Download Coubs ###

  [1/1] https://coub.com/view/19452g   ... finished

### Finished ###

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001A32E58F790>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001A32E58F790>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001A32E58F790>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

```
![image](https://user-images.githubusercontent.com/11407417/159170707-8187e591-1a1c-403c-bfee-8d569c5f35ed.png)

**Comment by Magellano** [comment]
> Works with the new hotfix release on my Win10 machine. !

Do you mean a hotfix for Win 10? Do you think it depends on the build version?

**Comment by Magellano** [comment]
> Works with the new hotfix release on my Win10 machine.

I didn't notice right away that you published a hotfix. It seems that now the script processes the characters and the download is successful. Thank you for your script and for your help

**Comment by HelpSeeker** [comment]
Glad to hear. Then I'm closing this now.
