### ISSUE TITLE
Error when trying to batch download from a channel.

### ISSUE THREAD

**Issue by crecca** [HelpSeeker/CoubDownloader#17]
When I download a single coub by id, it works just fine. When I add a channel name, it finds the channel, finds the links, but fails to start downloading the coubs. Any ideas? Using the hotfix version with the GUI.

```
### Parse Input ###

Downloading channel info: credible2 (sorted by 'most_recent')
  12 out of 12 pages

Results:
  279 links

### Download Coubs ###

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002AA3EF18A60>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 116, in __del__
  File "asyncio\proactor_events.py", line 108, in close
  File "asyncio\base_events.py", line 751, in call_soon
  File "asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
... this goes on for like 15 times
```

And in the separate error window:
```
Traceback (most recent call last):
  File "coub-gui.py", line 303, in <module>
  File "coub.py", line 1995, in main
  File "coub.py", line 1960, in attempt_process
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "coub.py", line 1929, in process
  File "coub.py", line 1096, in process
  File "coub.py", line 941, in parse
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by crecca** [comment]
Figured out that IF the channel itself is empty with 0 videos, (I only wanted to pull down my hundreds of recoubed coubs), then this error happens. Rare exception I guess.

**Comment by crecca** [comment]
Nope it downloads 5 videos, and hits me with basically the same error message.

**Comment by HelpSeeker** [comment]
It shouldn't happen for empty channels. In that case you should get something like
```
Downloading channel info: x (sorted by 'y')
  0 out of 0 pages
```

This particular error happens, when the Coub API is unstable/temporarily not available. Instead of providing a JSON response (like you'd expect from the API), they send the generic error webpage back. I fixed this in Gyre, but never backported it to CoubDownloader. I can't do anything about the API not sending a proper response, but I can make CoubDownloader handle the error gracefully and register it as a failed connection attempt.

I'll get to it as soon as I get back to my PC.

**Comment by HelpSeeker** [comment]
Fixed in the dev version. Master following soon.

**Comment by HelpSeeker** [comment]
Should be fixed in the newest hotfix version. Again, I can't do anything about the Coub API having connection issues (this problem has plagued me many times, but usually resolves itself after a day), but it should now be properly handled by trying to reconnect.

**Comment by crecca** [comment]
Thanks for trying and recompiling so quickly, still dropped the connection after 5 downloads with the latest build.
However, when I drop the connection number from the default 25 in the gui to only 1, then it seems to fix the problem. Now it's at the 35th download and not dropping connection. So my guess is there are some kind of 'hammering' protection on the server that blocks access temporarily.

**Comment by HelpSeeker** [comment]
Coub does shut down connections, if you try too many, but 25 is usually more than safe. I only ever ran into serious issues when experimenting with over 100 connections.

These API connection issues are rather arbitrary. Often enough you can download tens of thousands coubs a day without a problem and then there are days, where you have to retry every second coub.

Anyway, I'm happy that you found a workaround for the issue. Hopefully the connection gets better for you soon.
