### ISSUE TITLE
i cant actiavate can you help

### ISSUE THREAD

**Issue by muhammed06C** [HelpSeeker/CoubDownloader#22]
how can i build this project can you tell me with photos

**Comment by muhammed06C** [comment]
can you share exe file with mail

**Comment by muhammed06C** [comment]
https://github.com/HelpSeeker/CoubDownloader

**Comment by HelpSeeker** [comment]
Have you tried the standalone builds from the release page yet?
https://github.com/HelpSeeker/CoubDownloader/releases/tag/v3.7

**Comment by muhammed06C** [comment]
you're the best ı reliefed last year ı downloaded manually its wasnt good expreince 
ı need one help 
can we download with original names ı mean title of the video

**Comment by muhammed06C** [comment]
ı find it

**Comment by HelpSeeker** [comment]
Good. Do you need help with anything else?

**Comment by muhammed06C** [comment]
I'm using it now and I learned how to use it, it's very simple and comfortable and you shared it with us. 
i am very happy about it thank you for all of this
