### ISSUE TITLE
about the download file format

### ISSUE THREAD

**Issue by kaliludan** [HelpSeeker/CoubDownloader#6]
the script itself is amazing, thanks.
However, MKV is a very editing-unfriendly format, is there a way I can change the download file format default setting into mp4? I am not a programmer so this may sound like a stupid request.

**Comment by HelpSeeker** [comment]
> is there a way I can change the download file format default setting into mp4?

There is after the latest commit. Look for `merge_ext` in the advanced options section (bottom of the Options class) and change `mkv` to `mp4`.

It works from what I can tell, but I only did a few quick tests. If you encounter any problems, please let me know.

**Comment by HelpSeeker** [comment]
Ah. Didn't know that mentioning the issue in the commit message automatically closes it. My bad.

**Comment by HelpSeeker** [comment]
Haven't encountered any problems in the meantime, so this should be resolved.
